### ISSUE TITLE
2.11.6版本的nodejs.sdk调用cos.multipartUpload报错XML格式不对

### ISSUE THREAD

**Issue by littersnaker** [tencentyun/cos-nodejs-sdk-v5#131]
服务端报错信息如下   
![image](https://user-images.githubusercontent.com/36786281/149753949-d7bc2337-0987-46e2-ab38-c34406b56c09.png)
参数图片如下
![1642415524(1)](https://user-images.githubusercontent.com/36786281/149753981-020d1888-8ed8-44e5-8a78-ff1a32fcdacc.jpg)
查询文档是说XML类型错误

**Comment by littersnaker** [comment]
MalformedXML: The XML you provided was not well-formed or did not validate against our published schema.
    at Request.endHandler (D:\workCode\pic-backend\node_modules\cos-nodejs-sdk-v5\sdk\base.js:3818:35)
    at Request.emit (events.js:327:22)
    at IncomingMessage.<anonymous> (D:\workCode\pic-backend\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'MalformedXML',

**Comment by littersnaker** [comment]
参数格式   Parts: [
    { ETag: '"b2162500d9f991152205bc48f9b27b52"', PartNumber: 0 },
    { ETag: '"697731be1adcf196c450b4e946d645f8"', PartNumber: 1 },
    { ETag: '"42abeaca4302b4c05675ece6fb27227a"', PartNumber: 2 },
    { ETag: '"563272d4afd02e0ab37192ab065e61a6"', PartNumber: 3 },
    { ETag: '"67c89399c4cd07025cee73b74398e948"', PartNumber: 4 },
    { ETag: '"a8915f7c9dd712087caeeee5265ddff6"', PartNumber: 5 }
  ]

**Comment by littersnaker** [comment]
![1642415524(1)](https://user-images.githubusercontent.com/36786281/149753783-a0291b05-cb48-49fc-ac33-f38452623f01.jpg)
