### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by isNeilLin** [tencentyun/cos-nodejs-sdk-v5#23]
使用putObject上传一个音频文件，报这样的错误。
```
{ error:
   { Error: socket hang up
       at createHangUpError (_http_client.js:344:15)
       at Socket.socketOnEnd (_http_client.js:436:23)
       at emitNone (events.js:110:20)
       at Socket.emit (events.js:207:7)
       at endReadableNT (_stream_readable.js:1047:12)
       at _combinedTickCallback (internal/process/next_tick.js:102:11)
       at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' } }
```

这是上传文件的代码：
```
const saveAudio = (ctx, audio, id)=>{
    return new Promise((resolve, reject)=>{
        const { name, mimetype } = audio
        if(mimetype.indexOf('audio')==-1){
            resolve({
                code: 1,
                msg: '文件格式错误'
            })
        }
        let location = `audios/${name}`;
        let param = Object.assign({},baseParam,{
            Key: location,
            Body: audio,
            ContentType: 'application/octet-stream',
            ContentLength: ctx.request.length,
            onProgress: function (progressData) {
                console.log(progressData);
            }
        })
        cos.putObject(param,function(err,data){
            if(err){
                console.log(err)
                reject(err)
            }
            resolve({
                name: name,
                src: baseSrc+location
            })
        })
    })
}
```
param部分
```
 {
    Bucket: myBucket,
    Region: 'cn-north',
    Key: 'audios/test.mp3',
    Body: audio, // 可写流
    ContentType: 'application/octet-stream',
    ContentLength: ctx.request.length,
    onProgress: function (progressData) {
           console.log(progressData);
    }
}
```

**Comment by carsonxu** [comment]
audio怎么生成的？

**Comment by isNeilLin** [comment]
postman本地上传的。上传的格式是formdata

**Comment by isNeilLin** [comment]
每次都是上传到 precent 0.99就报错了
```
{ loaded: 11599872,
  total: 15289568,
  speed: 10622593.4,
  percent: 0.75 }
{ loaded: 15288862,
  total: 15289568,
  speed: 3670636.81,
  percent: 0.99 }
{ loaded: 15288862, total: 15289568, speed: 0, percent: 0.99 }
```

**Comment by isNeilLin** [comment]
audio的readable为true
```
PassThrough {
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: [Object], tail: [Object], length: 1 },
     length: 15288862,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: true,
     endEmitted: false,
     reading: false,
     sync: false,
     needReadable: false,
     emittedReadable: true,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: { end: { [Function: bound onceWrapper] listener: [Function: onend] } },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: true,
     ended: true,
     finished: true,
     destroyed: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: false,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: true,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: false,
  allowHalfOpen: true,
  _transformState:
   TransformState {
     afterTransform: [Function],
     needTransform: false,
     transforming: false,
     writecb: null,
     writechunk: null,
     writeencoding: 'buffer' },
  name: '许巍 - 在别处 (Live).mp3',
  mimetype: 'audio/mpeg',
  encoding: '7bit' }
```

**Comment by isNeilLin** [comment]
@carsonxu  可以了。PassThrough转换流不行，用ReadStream可以了

**Comment by carsonxu** [comment]
ok
