### ISSUE TITLE
网络中断错误

### ISSUE THREAD

**Issue by samrama** [tencentyun/cos-nodejs-sdk-v5#33]
D:\visualization-server\node_modules\cos-nodejs-sdk-v5\sdk\base.js:131
        var contents = data.ListBucketResult.Contents || [];
                                             ^

TypeError: Cannot read property 'Contents' of undefined
    at D:\visualization-server\node_modules\cos-nodejs-sdk-v5\sdk\base.js:131:46
    at cb (D:\visualization-server\node_modules\cos-nodejs-sdk-v5\sdk\base.js:2073:13)
    at Request.<anonymous> (D:\visualization-server\node_modules\cos-nodejs-sdk-v5\sdk\base.js:2119:29)
    at Request.emit (events.js:164:20)
    at IncomingMessage.<anonymous> (D:\visualization-server\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

网络中断 会出现错误

**Comment by carsonxu** [comment]
已优化容错
