### ISSUE TITLE
throw new Error('"start" option must be <= "end" option');

### ISSUE THREAD

**Issue by samrama** [tencentyun/cos-nodejs-sdk-v5#34]
"cos-nodejs-sdk-v5": "^2.3.6"

2018-04-09 10:38:12.723 58f05b19  Error: "start" option must be <= "end" option
2018-04-09 10:38:12.723 58f05b19      at new ReadStream (fs.js:1962:13)
2018-04-09 10:38:12.724 58f05b19      at Object.fs.createReadStream (fs.js:1923:10)
2018-04-09 10:38:12.724 58f05b19      at COS.uploadSliceItem (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/advance.js:486:19)
2018-04-09 10:38:12.724 58f05b19      at /var/www/node_modules/cos-nodejs-sdk-v5/sdk/advance.js:420:25
2018-04-09 10:38:12.724 58f05b19      at replenish (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/async.js:19:13)
2018-04-09 10:38:12.724 58f05b19      at Object.eachLimit (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/async.js:35:7)
2018-04-09 10:38:12.724 58f05b19      at COS.uploadSliceList (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/advance.js:415:11)
2018-04-09 10:38:12.724 58f05b19      at Array.<anonymous> (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/advance.js:54:25)
2018-04-09 10:38:12.724 58f05b19      at EventProxy.cos.emit (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/event.js:24:20)
2018-04-09 10:38:12.725 58f05b19      at /var/www/node_modules/cos-nodejs-sdk-v5/sdk/advance.js:95:20
2018-04-09 10:38:12.725 58f05b19      at Array.<anonymous> (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/advance.js:241:9)
2018-04-09 10:38:12.725 58f05b19      at EventProxy.cos.emit (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/event.js:24:20)
2018-04-09 10:38:12.725 58f05b19      at /var/www/node_modules/cos-nodejs-sdk-v5/sdk/advance.js:261:16
2018-04-09 10:38:12.725 58f05b19      at _callback (/var/www/node_modules/cos-nodejs-sdk-v5/sdk/util.js:295:25)
2018-04-09 10:38:12.725 58f05b19      at /var/www/node_modules/cos-nodejs-sdk-v5/sdk/base.js:1494:20

**Comment by carsonxu** [comment]
这里是 分片大小传了 10 导致出错，已修复这个问题，加了容错
