### ISSUE TITLE
上传文件时ECONNRESET

### ISSUE THREAD

**Issue by orangemi** [tencentyun/cos-nodejs-sdk-v5#4]
用demo上传文件时

以下是config
```
    Bucket: 'tbtest',
    Region: 'cossh'
```

以下是log
```
node node_modules/cos-nodejs-sdk-v5/demo/demo.js
1mb.zip create success
{ error:
   { Error: socket hang up
       at createHangUpError (_http_client.js:302:15)
       at Socket.socketOnEnd (_http_client.js:394:23)
       at emitNone (events.js:91:20)
       at Socket.emit (events.js:188:7)
       at endReadableNT (_stream_readable.js:975:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' } }
```

**Comment by orangemi** [comment]
问题找到了，region应该改成`cn-east`
