### ISSUE TITLE
这是什么情况

### ISSUE THREAD

**Issue by lxzan** [tencentyun/cos-nodejs-sdk-v5#45]
{ loaded: 20215, total: 10485760, speed: 18511.9, percent: 0 }
{ loaded: 20215, total: 10485760, speed: 0, percent: 0 }
{ error: { Error: socket hang up
    at createHangUpError (_http_client.js:312:15)
    at TLSSocket.socketOnEnd (_http_client.js:405:23)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1091:14)
    at process._tickCallback (internal/process/next_tick.js:174:19) code: 'ECONNRESET' } }

**Comment by carsonxu** [comment]
这里发请求调用了 https://www.npmjs.com/package/request 模块，看错误像是网络不稳定。
是否并发数过多？
