### ISSUE TITLE
TypeError: params.outputStream.on is not a function

### ISSUE THREAD

**Issue by WizTeam** [tencentyun/cos-nodejs-sdk-v5#57]
2018-09-26 08:34 +08:00: TypeError: params.outputStream.on is not a function
    at COS._submitRequest (/wiz/app/wizserver.20180925.1736/node_modules/cos-nodejs-sdk-v5/sdk/base.js:2268:29)
    at /wiz/app/wizserver.20180925.1736/node_modules/cos-nodejs-sdk-v5/sdk/base.js:2061:24

这个是什么错误？

**Comment by WizTeam** [comment]
2018-09-26 08:34 +08:00: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at /wiz/app/wizserver.20180925.1736/node_modules/cos-nodejs-sdk-v5/sdk/base.js:1037:34
    at cb (/wiz/app/wizserver.20180925.1736/node_modules/cos-nodejs-sdk-v5/sdk/base.js:2139:13)
    at Request.<anonymous> (/wiz/app/wizserver.20180925.1736/node_modules/cos-nodejs-sdk-v5/sdk/base.js:2161:17)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)

还有这个错误

**Comment by carsonxu** [comment]
这两个问题最后有没有解决？

**Comment by WizTeam** [comment]
> 这两个问题最后有没有解决？

网络不好的时候会出现，没有解决
