### ISSUE TITLE
putObject方法使用http response流上传失败，Error: socket hang up

### ISSUE THREAD

**Issue by pyuyu** [tencentyun/cos-nodejs-sdk-v5#94]
```javascript
const res = await this.axios.post(`https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=${accessToken}`, { page, scene, }, { responseType: 'stream' })
cos.putObject({
  Bucket: currentBucket.Bucket,
  Region: config.Region,
  Key: fileName,
  Body: res.data,
  ContentLength: res.headers['content-length'],
  onProgress: progressData => {
    console.log(JSON.stringify(progressData));
  },
}, (err, data = {}) => {
  if (data.statusCode === 200) {
    console.log(data)
  } else {
    console.log(err)
  }
})
```

输出：
```
{"loaded":0,"total":97042,"speed":0,"percent":0}
{"loaded":81714,"total":97042,"speed":70993.92,"percent":0.84}
{"loaded":81714,"total":97042,"speed":0,"percent":0.84}
{
  error: [Error: socket hang up
    at connResetException (internal/errors.js:614:14)
    at TLSSocket.socketOnEnd (_http_client.js:491:23)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
  ] {
    code: 'ECONNRESET'
  }
}
```

**Comment by pyuyu** [comment]
找到问题了， 在上传前用了`FileType.fromStream(stream)`， 应该是这把steam消费了

**Comment by carsonxu** [comment]
谢谢反馈问题和原因。
